
#************************************************************
# file: Makefile
#
#  4. Jun. 03  hstabena Adapted to new environment
#
#************************************************************

all::
	cd src && $(MAKE) $@

clean::
	cd src && $(MAKE) $@

install::
	cd src && $(MAKE) $@
